[package]
name = "tidymedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
generic-array = "0"
hex = "*"
ignore = "*"
memmap2 = "*"
rayon = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"
tempfile = "*"
thiserror = "*"
time = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
wyhash = "*"
xxhash-rust = { version = "*", features = ["xxh3"] }
