[package]
name = "tidymedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
futures = "0.3"
generic-array = "0"
hex = "0.4"
ignore = "0.4"
sha2 = "0.10"
tokio = {version = "1", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
wyhash = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

