[package]
name = "tidymedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.9"
crc32fast = "1.3.2"
generic-array = "0.14.5"
hex-literal = "0.3.4"
log = "0.4.16"
sha2 = "0.10.2"
